name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "GCC.tar.xz",
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest Clang", artifact: "Clang.tar.xz",
            build_type: "Release", cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: mkdir build
    - name: Install dependencies
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan install -if build .
    - name: Build project
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        cd build
        cmake --configure ..
        cmake --build .
    - name: Run tests
      run: |
        ln -s `pwd`/tests/fixtures build/tests/fixtures
        cd build
        ctest --output-on-failure
